# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "967818fbca3c3c5115744d6f2bc26862"
name = "free-gift-comercial-qure-app"
handle = "free-gift-comercial-qure-app"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "endrock-tech-test-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_cart_transforms,read_products,write_cart_transforms,write_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
